name: remote

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:

      # - name: Tailscale
      #   uses: tailscale/github-action@v3
      #   with:
      #     oauth-client-id: ${{ secrets.TAILSCALE_CLIENTID }}
      #     oauth-secret: ${{ secrets.TAILSCALE_SECRET }}
      #     tags: tag:actions
      #     use-cache: 'true'
      #     args: --ssh

      - shell: bash
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/AppleVNCServer.bundle/Contents/MacOS/AppleVNCServer
          
      - name: Enable RDP
        uses: gbraad-actions/enable-mac-remote@main
        with:
          vnc_password: vncvncvnc

      - run: |
          curl https://aka.ms/TunnelsCliDownload/osx-x64 -L -J --output devtunnel

      - run: |
          sudo chmod -R +x . && \
          ./devtunnel user login -g -d
      
      - run: |
          ./devtunnel host -p 5900 --allow-anonymous --protocol auto
          
      # - name: Hang around
      #   if: ${{ always() }}
      #   run: |
      #     sleep 21600
