name: remote

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:

      # - name: 'Enable Screen Sharing'
      #   shell: bash
      #   run: |
      #     sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
  
      # - name: 'Configure Access for Specified User'
      #   shell: bash
      #   run: |
      #     sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
      #       -configure -allowAccessFor -specifiedUsers
      #     sudo dscl . create /Groups/com.apple.remote.management
      #     sudo dscl . create /Groups/com.apple.remote.management PrimaryGroupID 404
      #     sudo dscl . create /Groups/com.apple.remote.management RealName "Remote Management Group"
      #     sudo dseditgroup -o edit -a "${{ inputs.allowed_user }}" -t user com.apple.remote.management
  
      # - name: 'Enable Remote Management'
      #   shell: bash
      #   run: |
      #     sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
      #       -activate -configure -access -on \
      #       -clientopts -setvnclegacy -vnclegacy yes \
      #       -clientopts -setvncpw -vncpw "${{ inputs.vnc_password }}" \
      #       -restart -agent -privs -all
  
      # - name: 'Allow Remote Management Through Firewall'
      #   shell: bash
      #   run: |
      #     sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/MacOS/ARDAgent
      #     sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/MacOS/ARDAgent


      # - name: Tailscale
      #   uses: tailscale/github-action@v3
      #   with:
      #     oauth-client-id: ${{ secrets.TAILSCALE_CLIENTID }}
      #     oauth-secret: ${{ secrets.TAILSCALE_SECRET }}
      #     tags: tag:actions
      #     use-cache: 'true'
      #     args: --ssh

      - shell: bash
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/AppleVNCServer.bundle/Contents/MacOS/AppleVNCServer
          
      - name: Enable RDP
        uses: gbraad-actions/enable-mac-remote@main
        with:
          vnc_password: vncvncvnc

      - run: |
          curl https://aka.ms/TunnelsCliDownload/osx-x64 -L -J --output devtunnel

      - run: |
          sudo chmod -R +x . && \
          ./devtunnel user login -g -d
      
      - run: |
          ./devtunnel host -p 5900 --allow-anonymous --protocol auto
          
      # - name: Hang around
      #   if: ${{ always() }}
      #   run: |
      #     sleep 21600
